#!/usr/bin/env node
/**
 * Emits DDL for both providers from scripts/schema.models.prisma:
 *   apps/api/prisma/sql/postgresql.sql   (production)
 *   apps/api/prisma/sql/sqlite.sql       (local dev / CI / tests)
 *
 * Prisma 7 uses a WASM query compiler + driver adapters at runtime, so no
 * engine binary is needed to *query*. This generator replaces `prisma migrate`
 * for environments without access to binaries.prisma.sh, and the checked-in SQL
 * doubles as the reviewable migration artifact for production deploys.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const src = readFileSync(join(root, 'scripts', 'schema.models.prisma'), 'utf8');

/* ------------------------------- parsing --------------------------------- */

function stripComments(line) {
  const i = line.indexOf('//');
  return (i === -1 ? line : line.slice(0, i)).trim();
}

function parseModels(text) {
  // Remove block comments.
  const cleaned = text.replace(/\/\*[\s\S]*?\*\//g, '');
  const models = [];
  const re = /model\s+(\w+)\s*\{([\s\S]*?)\n\}/g;
  let m;
  while ((m = re.exec(cleaned))) {
    const [, name, body] = m;
    const fields = [];
    const indexes = [];
    let pkCompound = null;

    for (const raw of body.split('\n')) {
      const line = stripComments(raw);
      if (!line) continue;

      if (line.startsWith('@@index')) {
        const cols = line.match(/@@index\(\[([^\]]+)\]/)?.[1];
        if (cols) indexes.push(cols.split(',').map((c) => c.trim()));
        continue;
      }
      if (line.startsWith('@@unique')) {
        const cols = line.match(/@@unique\(\[([^\]]+)\]/)?.[1];
        if (cols) indexes.push({ unique: true, cols: cols.split(',').map((c) => c.trim()) });
        continue;
      }
      if (line.startsWith('@@id')) {
        pkCompound = line.match(/@@id\(\[([^\]]+)\]/)?.[1]?.split(',').map((c) => c.trim()) ?? null;
        continue;
      }
      if (line.startsWith('@@')) continue;

      const fm = line.match(/^(\w+)\s+(\w+)(\[\])?(\?)?\s*(.*)$/);
      if (!fm) continue;
      const [, fname, ftype, list, optional, attrs] = fm;

      fields.push({
        name: fname,
        type: ftype,
        isList: Boolean(list),
        optional: Boolean(optional),
        attrs: attrs || '',
        isId: /@id\b/.test(attrs),
        isUnique: /@unique\b/.test(attrs),
        relation: /@relation\(/.test(attrs) ? attrs.match(/@relation\(([^)]*)\)/)?.[1] ?? '' : null,
        default: attrs.match(/@default\(([^)]*(?:\([^)]*\))?[^)]*)\)/)?.[1] ?? null,
        updatedAt: /@updatedAt/.test(attrs),
      });
    }
    models.push({ name, fields, indexes, pkCompound });
  }
  return models;
}

const models = parseModels(src);
const modelNames = new Set(models.map((m) => m.name));

/* ------------------------------- emitting -------------------------------- */

const SCALARS = new Set(['String', 'Int', 'Float', 'Boolean', 'DateTime', 'Json', 'BigInt', 'Decimal']);

function sqlType(field, dialect) {
  const pg = dialect === 'pg';
  switch (field.type) {
    case 'String':
      return pg ? 'TEXT' : 'TEXT';
    case 'Int':
      return pg ? 'INTEGER' : 'INTEGER';
    case 'Float':
      return pg ? 'DOUBLE PRECISION' : 'REAL';
    case 'Boolean':
      return pg ? 'BOOLEAN' : 'INTEGER';
    case 'DateTime':
      return pg ? 'TIMESTAMPTZ(3)' : 'DATETIME';
    case 'Json':
      return pg ? 'JSONB' : 'TEXT';
    default:
      return 'TEXT';
  }
}

function defaultClause(field, dialect) {
  if (field.default === null) return '';
  const d = field.default.trim();
  const pg = dialect === 'pg';

  if (d === 'now()') return pg ? ' DEFAULT CURRENT_TIMESTAMP' : ' DEFAULT CURRENT_TIMESTAMP';
  if (d === 'cuid()' || d === 'uuid()' || d === 'autoincrement()') return ''; // generated app-side by Prisma
  if (d === 'true') return pg ? ' DEFAULT true' : ' DEFAULT 1';
  if (d === 'false') return pg ? ' DEFAULT false' : ' DEFAULT 0';
  if (/^".*"$/.test(d)) return ` DEFAULT '${d.slice(1, -1).replace(/'/g, "''")}'`;
  if (/^-?\d+(\.\d+)?$/.test(d)) return ` DEFAULT ${d}`;
  return '';
}

function quote(name, dialect) {
  return dialect === 'pg' ? `"${name}"` : `"${name}"`;
}

function build(dialect) {
  const out = [];
  const pg = dialect === 'pg';
  out.push('-- AUTO-GENERATED by scripts/gen-sql.mjs — do not edit by hand.');
  out.push(`-- Dialect: ${pg ? 'PostgreSQL' : 'SQLite'}`);
  out.push('-- Source of truth: scripts/schema.models.prisma');
  out.push('');
  if (!pg) out.push('PRAGMA foreign_keys = ON;', '');

  const fkStatements = [];

  for (const model of models) {
    const cols = [];
    const tableFks = [];

    for (const f of model.fields) {
      if (!SCALARS.has(f.type)) {
        // Relation field — emit FK only on the side that carries @relation(fields:)
        if (f.relation && f.relation.includes('fields:')) {
          const fieldsList = f.relation.match(/fields:\s*\[([^\]]+)\]/)?.[1]?.split(',').map((s) => s.trim()) ?? [];
          const refList = f.relation.match(/references:\s*\[([^\]]+)\]/)?.[1]?.split(',').map((s) => s.trim()) ?? [];
          const onDelete = f.relation.match(/onDelete:\s*(\w+)/)?.[1] ?? 'Restrict';
          const map = { Cascade: 'CASCADE', SetNull: 'SET NULL', Restrict: 'RESTRICT', NoAction: 'NO ACTION' };
          if (fieldsList.length && refList.length && modelNames.has(f.type)) {
            tableFks.push(
              `  FOREIGN KEY (${fieldsList.map((c) => quote(c, dialect)).join(', ')}) REFERENCES ${quote(f.type, dialect)}(${refList
                .map((c) => quote(c, dialect))
                .join(', ')}) ON DELETE ${map[onDelete] ?? 'RESTRICT'} ON UPDATE CASCADE`,
            );
          }
        }
        continue;
      }
      if (f.isList) continue;

      let col = `  ${quote(f.name, dialect)} ${sqlType(f, dialect)}`;
      if (f.isId) col += ' PRIMARY KEY';
      else if (!f.optional) col += ' NOT NULL';
      col += defaultClause(f, dialect);
      cols.push(col);
    }

    if (model.pkCompound) {
      cols.push(`  PRIMARY KEY (${model.pkCompound.map((c) => quote(c, dialect)).join(', ')})`);
    }

    out.push(`CREATE TABLE IF NOT EXISTS ${quote(model.name, dialect)} (`);
    out.push([...cols, ...tableFks].join(',\n'));
    out.push(');');
    out.push('');

    // Unique + regular indexes
    for (const f of model.fields) {
      if (f.isUnique && SCALARS.has(f.type)) {
        out.push(
          `CREATE UNIQUE INDEX IF NOT EXISTS ${quote(`${model.name}_${f.name}_key`, dialect)} ON ${quote(model.name, dialect)}(${quote(f.name, dialect)});`,
        );
      }
    }
    for (const idx of model.indexes) {
      const unique = Array.isArray(idx) ? false : idx.unique;
      const cols2 = Array.isArray(idx) ? idx : idx.cols;
      const iname = `${model.name}_${cols2.join('_')}_idx`;
      out.push(
        `CREATE ${unique ? 'UNIQUE ' : ''}INDEX IF NOT EXISTS ${quote(iname, dialect)} ON ${quote(model.name, dialect)}(${cols2
          .map((c) => quote(c, dialect))
          .join(', ')});`,
      );
    }
    out.push('');
  }

  out.push(...fkStatements);
  return out.join('\n');
}

const dir = join(root, 'apps', 'api', 'prisma', 'sql');
mkdirSync(dir, { recursive: true });
writeFileSync(join(dir, 'postgresql.sql'), build('pg'));
writeFileSync(join(dir, 'sqlite.sql'), build('sqlite'));
console.log(`[gen-sql] wrote postgresql.sql + sqlite.sql for ${models.length} models`);
