#!/usr/bin/env node
/**
 * Generates apps/api/prisma/schema.prisma.
 *
 * Production runs PostgreSQL. Local dev / CI / this sandbox may not have a
 * Postgres server, so the same model set is emitted against SQLite when
 * DATABASE_URL is absent or starts with `file:`. Field types are deliberately
 * provider-agnostic (no native enums, no scalar lists) so the two builds stay
 * byte-for-byte identical apart from the datasource block.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const apiDir = join(root, 'apps', 'api');

// Load apps/api/.env without a dependency.
const envPath = join(apiDir, '.env');
let envUrl = process.env.DATABASE_URL;
if (!envUrl && existsSync(envPath)) {
  const match = readFileSync(envPath, 'utf8').match(/^DATABASE_URL\s*=\s*"?([^"\n]+)"?/m);
  if (match) envUrl = match[1];
}

const url = envUrl || 'file:./dev.db';
const provider = url.startsWith('postgres') ? 'postgresql' : 'sqlite';

const models = readFileSync(join(root, 'scripts', 'schema.models.prisma'), 'utf8');

const header = `// AUTO-GENERATED by scripts/gen-schema.mjs — do not edit by hand.
// Provider resolved from DATABASE_URL: ${provider}
// Edit scripts/schema.models.prisma instead, then run \`npm run db:schema\`.
//
// Prisma 7: the connection URL lives in prisma.config.ts / the driver adapter
// passed to PrismaClient, not in this file.

generator client {
  provider = "prisma-client"
  output   = "../src/generated/prisma"
  moduleFormat = "esm"
}

datasource db {
  provider = "${provider}"
}
`;

mkdirSync(join(apiDir, 'prisma'), { recursive: true });
writeFileSync(join(apiDir, 'prisma', 'schema.prisma'), `${header}\n${models}`);
console.log(`[gen-schema] wrote apps/api/prisma/schema.prisma (provider=${provider})`);
